-- Deploy training_API_scripts:version_1 to pg

BEGIN;

CREATE TABLE "movie" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" TEXT NOT NULL,
    "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamptz
);

COMMIT;
